### ISSUE TITLE
Interaction Engine: Controllers are not found, when app starts too fast

### ISSUE THREAD

**Issue by Tom-LeFx** [leapmotion/UnityModules#1021]
Issue in Interaction Engine Modules for Unity, even in example scenes.

Steps to reproduce:

- Deactivate Splash Screen (from Unity or any other one)
- Make a build, containing only this one level, which gets loaded on startup
- find yourself without working controllers

---
Alternative reproduction (like we found out about it):

- Import SteamVR (for examplen when you want to enable haptic controller feedback)
- let it adjust all suggested player settings (e.g. disable splash, etc)
- build any level, that directly starts as VR
- no hands

This should really be looked at, or at least be documented. 

Kind of the same direction:

If controllers are not turned on and detected at app-start, they will not be found later on. SteamVR/VRTK handles this without any issues...Leap Interaction Engine requires them to be present and active on startup

**Comment by nickjbenson** [comment]
Thanks for the ticket! I'm investigating.

We made this decision originally because the method to detect controllers allocates garbage. Looking at Unity's SDK, they still recommend using `Input.GetJoystickNames()`, which allocates garbage to returns a `string[]`:
https://docs.unity3d.com/ScriptReference/Input.GetJoystickNames.html

I find this to be pretty terrible! We've taken a lot of care to prevent the Interaction Engine from ever allocating garbage, because GC collects kill frames and make people sick. Unfortunately we may have to accept some periodic allocation from our example scene's controller detection script in order to address this issue.

**Comment by nickjbenson** [comment]
OK, we're getting https://github.com/leapmotion/UnityModules/pull/1022 reviewed for our latest release, which should address this issue.

**Comment by nickjbenson** [comment]
It is still suspicious to me that you say you're able to produce a scenario where you aren't even getting hand data. Do your non-SteamVR repro steps also prevent hand data from appearing in the application?
@Tom-LeFx

**Comment by nickjbenson** [comment]
Circling back again. We found another issue with controller initialization and the fix is being vetted before we apply it to all of our example scenes.
https://github.com/leapmotion/UnityModules/pull/1024
