### ISSUE TITLE
InteractionChecks.cs uses EditorApplication API which is unsupported on Unity 5.6

### ISSUE THREAD

**Issue by julienkay** [leapmotion/UnityModules#1045]
Unity changed the capitalisation in `playmodeStateChanged` to `playModeStateChanged` after 5.6
The script also uses the PlayModeStateChange enum which wasn't there in 5.6

Only writing this, since on the LM site for the Unity assets it says 5.6 is still supported.

P.S.: Nice work on the new version by the way :)

**Comment by nickjbenson** [comment]
Fixed in `develop` now! Future release packages will support 5.6 as advertised. We may hotfix a release to support 5.6 depending on how many 5.6ers we find.

The fixes are in these two commits:
https://github.com/leapmotion/UnityModules/commit/ab1210e3f4e708fdf066b5edac88c0c6407c6d6a
^fixes 5.6 support
https://github.com/leapmotion/UnityModules/commit/9248dc014c662cd28fb28403e6b2410e34c07c81
