### ISSUE TITLE
Leap Motion Core Version 4.4.0  if Scale !=1  Hand Mesh Deformation occurred

### ISSUE THREAD

**Issue by XinYueStudio** [leapmotion/UnityModules#1066]

**Comment by nickjbenson** [comment]
For now, this is a known issue with our rigged hand models for which we don't have a fix in the pipeline. Hands need to be rendered at unit scale to deform correctly. I haven't looked deeply into this because our demos are all built at unit scale: 1 Unity Unit == 1 Meter.

It should be possible to scale the model of a rigged hand to compensate for the increased bone length, but it's not something we support currently.

**Comment by TomasElkomos** [comment]
We are now in 2020 Is there no solution?
@nickjbenson

**Comment by Ultraleap-Dan** [comment]
We currently have no plans to support this. However, it would be interesting to know more about your use case for this?

**Comment by raphaelsetin** [comment]
@Ultraleap-Dan I am also having the same problem and I was hoping Ultraleap would support this.

Currently we are working on a demo for our HMD device and that demo is scaled 10x, which wasn't an issue until now. I agree that the demo is not correctly scaled with the real world, and we could potentially make the demo to be correctly scaled too, but we tried that and it's not worth the effort. Doing an overall scale adjustment messes up with many aspects of our demo scene, so the best we can do is to place our hands very close to the camera for it to seem like it's in the correct scale -- though the distortion wouldn't be correct.

Anyways, it's really annoying that you guys haven't implemented a scaling feature in your SDK, and I really hope you do in the near future.
