### ISSUE TITLE
Can not find the example code for Unity

### ISSUE THREAD

**Issue by YoshiKitaguchi** [leapmotion/UnityModules#1084]
Hello,

I have just downloaded the zip file of LeapDeveloperKit_4.0.0_52238.
But I can not find Example code as it is said on http://blog.leapmotion.com/multiple-devices/.
Could you tell me where is the code?

sincerely,

**Comment by BeaXR** [comment]
I'm facing the same issue.
Please, could you add the example code?
Sincerely

**Comment by BeaXR** [comment]
Hello, 
you can find the example here:
https://github.com/leapmotion/UnityModules/tree/feat-multi-device
Look for the Multi-Device (Desktop) scene found in Assets/LeapMotion/Core/Examples
If you have errors in Unity (maybe due to a different version), as it happened to me, just delete the following folders:
- Assets/LeapMotion/Experimental
- Assets/LeapMotion/Modules/GraphicRenderer
I hope it was helpful
