### ISSUE TITLE
The model's hands will be deformed

### ISSUE THREAD

**Issue by Tidne** [leapmotion/UnityModules#1144]
When I go to match the hand of my own model, the character will be deformed, whether I set it manually or using an autorig script.
Especially when I set the palm value, my hands will be pulled to strange places.
![image](https://user-images.githubusercontent.com/29405397/101890885-47e58480-3bdc-11eb-8ac2-8f9c200e5739.png)

**Comment by Ultraleap-Dan** [comment]
This rigging method will be superseded by a new method for binding hands: https://github.com/leapmotion/UnityModules/pull/1157

**Comment by MaxPalmer-UH** [comment]
Please check out the new Hands Binder in the latest release.

**Comment by acmoles** [comment]
The new hand binder looks like a big improvement. Great work. 

I was particularly impressed with the promise of flipping left<>right hand models automatically in the bind. Sadly it looks like this doesn't work well in practice. Here's an example of the deformation that occurs with the included generic hand model:

![image](https://user-images.githubusercontent.com/15641910/121776305-08e0bd80-cb84-11eb-9a58-0cb872f7d062.png)

I tried passing my own models through the new bind process but faced strange deformations:

![image](https://user-images.githubusercontent.com/15641910/121776257-c3bc8b80-cb83-11eb-84b0-2f409ad03671.png)

These were working ok with the old process. The model closely follows the structure of the low poly hands. Can you offer any suggestions as to what the issue might be?

Thanks.

**Comment by ElliotPadfieldUL** [comment]
Hey @acmoles, the hand binder does not automatically flip the model's geometry for you this is something you will need to do first.

If you have a left-hand model, you can create a right-hand model from it by flipping the scale to negative. We do this in the outline hands prefab by duplicating the left hand, then flipping the model on the x-axis so that the new right hand is set to -1. After this, just make sure the hand binder is set to left or right.
