### ISSUE TITLE
Investigate changing IHandModel lifecycle callbacks

### ISSUE THREAD

**Issue by Amarcolina** [leapmotion/UnityModules#163]
This is the existing IHandModel lifecycle.
InitHand -> (BeginHand -> UpdateHand -> FinishHand -> BeginHand...)

This is very close, or identical to the default Unity Monobehaviour lifecycle.
(Awake/Start) -> (OnEnable -> Update/FixedUpdate -> OnDisable -> OnEnable ...)

It might make things easier on both us and developers if we tried to switch over to using the default MonoBehaviour lifecycle.  It could make it easier to develop new types of HandModel because one would be working within a framework that is more familiar.  It could also help prevent errors because we would not be keeping track of additional state that could become inconsistent.  It could also help prevent confusion (currently hand models can be disabled, but that means nothing...)

One possible proposal:
- Awake: Used for non-hand related initialization of the model
- OnEnable:  Called when a model begins tracking (comparable to BeginHand)
- Start: Called the first time a model begins tracking (comparable to InitHand)
- OnDisable:  Called when a model stops tracking (comparable to FinishHand)
- UpdateHand:  Still would be a custom callback to allow update ordering and the difference between Update and FixedUpdate to be automatic.

Not a complete proposal, but definitely something to think about.

**Comment by nickjbenson** [comment]
I like this idea, and I'd consider making HandModels follow a more familiar workflow to be a DevX issue

**Comment by nickjbenson** [comment]
Trying to flesh this out into an actionable proposal so the issue doesn't get stale.

If HandModels are MonoBehaviours and they are receiving MonoBehaviour callbacks, we can't necessarily guarantee that the conditions you're proposing are actually true when the callbacks are called. Specifically:

(1) What if the hand model GameObject is enabled when the Application begins playing? It will receive Awake and Start depending on its order of update relative to the Hand Model Manager. We could enforce an earlier scripting update time for the HandModelManager to prevent this from happening.
(2) What happens the user enables a hand model manually, but there's no tracking data for it? It _will_ receive Start() no matter what we do in that scenario, but the precondition was invalidated, because there was no tracking data.
(3) How do we have the model receive Awake() (to do non-hand-related initialization, so presumably before the hand is even tracked) but not Start() (because the hand hasn't been tracked)?

**Comment by Amarcolina** [comment]
I think I would be in favor of closing this issue, and in the back of our heads noodling on what kind of architecture we would build in the most ideal situation.  For example, what would everything look like if LeapC gave us a persistent left and right hand and that's it?  Lots of things would change, and the correct architecture might be more intuitive at that point.

**Comment by nickjbenson** [comment]
Agreed. I have a note to put together a meeting or two to talk about this and a body-centric model that can inform that work and communicate it to platform as well.

Closing this.
