### ISSUE TITLE
Serialization for LeapC

### ISSUE THREAD

**Issue by protodeep** [leapmotion/UnityModules#290]
Build serialization support in LeapC and in the C# wrapper.

**Comment by jselstad** [comment]
-Use LeapC Serialization for Hands/Frames
	-Defines File Format and Serialization Format
	-Construct Hands from Scene Skeleton, Lossy Tracking Frame, Animations, etc.
	-Construct Tracking Frames from Serialized Hand States
	-Hand Operation Functions
		-Interpolation between Hands
		-Distance between Hand Poses
		-Add/Subtract/Multiply/Divide(Hand2Vec?)

-New Unity Pose Authoring Tools (Save Tracking Pose Snapshot, Pose-Hand-In-Editor, Record Animation, etc.)
-New Unity Providers (ReplayProvider, NetworkProvider, AnimationProvider, etc.)

**Comment by codemercenary** [comment]
Are you going to be implementing the serialization system @jselstad?

**Comment by jselstad** [comment]
Probably not; just recording the thoughts we had from today's small conversation on Serialization and what it might encompass.  Since it's starting to seem like it might encompass a broader array of features, I made it an Epic (let me know if I'm misusing the term though).

We're going to brainstorm more heavily on exactly what a serialization system means to us and how it fits in with the rest of our assets tomorrow, after our stand-up.

**Comment by ajohnston33** [comment]
I already have a system for serializing and replaying both hands and entire animated scenes.  It is very stable, easy to debug, no bugs or performance issues.

**Comment by aroraenterprise** [comment]
@ajohnston33 Would you be willing to share this system? Is it an additional script in unity? I was thinking of writing one for Orion but every time I try to serialize the frame I get an indexoutofrangeexception...

**Comment by Amarcolina** [comment]
@aroraenterprise, currently serialization is in a work-in-progress state, but there are some options available to you if you need a solution now.  Currently, all the Leap classes (Frame / Hand / Finger / Bone ...) are tagged with the [Serializable] attribute and have friendly data layouts so that Unity can serialize them.  This means that while the functions existing in the class might throw an error, you can still use existing serialization techniques to save out these objects and load them back later (albeit at a much higher memory and performance cost).  You can see an example of this in the WIP Playback folder.

**Comment by Amarcolina** [comment]
We can now fully serialize leap frames and all sub objects.  If we want to scope out a *playback* system we can create a milestone for that
