### ISSUE TITLE
Pinch detector duplicates activate and deactivate variables

### ISSUE THREAD

**Issue by Amarcolina** [leapmotion/UnityModules#411]
Pinch Detector re-defines activate and deactivate distance, so it is there twice in the inspector, and the second set of values is not used for anything.

**Comment by nickjbenson** [comment]
Those are the original fields for pinch activation and deactivation distances before PinchDetector subclassed AbstractHoldDetector, which I assumed were carried over in the recent updates to allow upgrading developers to still have their customized distances carry over into their updated project by editor serialization. (That's what it did for me.)

If that was the intention, it's probably worth keeping for an update cycle with some notice that they are deprecated and then removing them in a future update.

**Comment by Amarcolina** [comment]
They are not named the same, so the values still show up in the inspector, but as duplicate values.  So in the inspector I have:

Activate Distance
Deactivate Distance 
Activate Pinch Distance
Deactivate Pinch Distance

And changing the last 2 doesn't have any affect.  We might be able to use the 'FormerlySerializedAsAttribute' that unity provides to do automatic serialization upgrades when we remove these variables though.

**Comment by nickjbenson** [comment]
Yeah. When I upgraded, the values I had tweaked for my PinchDetector were in those lower two fields because those were the original fields before my upgrade, so I was able to move them over to the actually-used fields. If I hadn't been looking at the source for it, I would have been confused. Agree that FormerlySerializedAs would be a good way to remove them without causing damage to old projects.
