### ISSUE TITLE
Remove ToUnity and ToUnityScaled

### ISSUE THREAD

**Issue by Amarcolina** [leapmotion/UnityModules#47]
Currently ToUnity and ToUnityScaled don't do anything different than ToVector3.  Either they should be changed so that they have a use, or they should be removed.

**Comment by jo3w4rd** [comment]
They have been restored to their former functionality. However, we should discuss whether to keep them anyway. There is a great potential for confusion and using them on an already transformed vector is a bad thing to do. On the other hand, if a developer gets a vector straight from the service rather than from the provider, the functions are useful.

**Comment by jo3w4rd** [comment]
After a bit more discussion, we have decided to remove them. Developers who get frames from a Controller are expected to know what they are doing.
