### ISSUE TITLE
Change wording of (VR) Visualizer on Mac

### ISSUE THREAD

**Issue by testmasterbright** [leapmotion/UnityModules#491]
##### Description:
Because there are no supported HMDs on Mac, we should change the wording on the VR Visualizer when an HMD is not detected.

Proposed change(s):
Instead of `"No head-mounted display detected. Orion performs best in a head-mounted display"`
Replace with `"Leap Motion Orion performs best in a head-mounted display"`

![screen shot 2017-01-18 at 2 42 00 pm](https://cloud.githubusercontent.com/assets/6034882/22086329/277dcbe6-dd8d-11e6-9e4d-3983095b8fd1.png)

**Comment by digitalweaver** [comment]
Honestly, I wonder if any message is needed. We are implicitly saying by releasing this version that the Mac version of Orion should work as well as V2 did for desktop. Since VR is not a use case for Mac should we be addressing it all? Or is the assumption being that peeps will be on their Mac using Leap Glasses to simulate VR and then porting to Windows? 

I think we will have people doing both desktop dev and VR dev.... So why point out that one is better?

**Comment by testmasterbright** [comment]
Well, to throw it out there we don't encourage desktop dev. I think we might be giving the wrong impression if we aren't pointing out that Orion was meant for VR.

**Comment by digitalweaver** [comment]
I get it. I just think to point it out on OS that does not support VR/AR currently doesn't really get us anything - how does the message benefit the user. It almost sounds like we are saying use at your risk?

**Comment by Anvil102** [comment]
Cloned issue for tracking in single repo: http://sf-github.leap.corp/leapmotion/platform/issues/7576

**Comment by nickjbenson** [comment]
Moved to the internal repo, so closing here.
