### ISSUE TITLE
Debug Hands are broken

### ISSUE THREAD

**Issue by jo3w4rd** [leapmotion/UnityModules#5]
Only a few lines of the fingers get drawn in Orion.

**Comment by Amarcolina** [comment]
A little info, since I noticed this issue as well when I was trying to get them working in the IE project.  it seems that there is a [HideInInspector] field that specifies which finger the FingerModel should reference, and since this defaults to FingerType.Index, all fingers represent index fingers.  My temp fix was to enter debug view to edit the otherwise hidden value, but that doesn't seem the the right fix to me.

**Comment by jo3w4rd** [comment]
Yes, in the old assets, the fingers were simply recreated each frame according to their array position, so this didn't matter. Now nothing actually sets the finger type field for FingerModel.
