### ISSUE TITLE
General fundamental Unity-level devX

### ISSUE THREAD

**Issue by Amarcolina** [leapmotion/UnityModules#515]
We should explore and implement the following:
 - Adding AddComponentMenu for *all* monobehaviors we create for maximum discoverability
 - Adding AddComponentMenu for all scripts we want to hide from the developer (like example scripts)
 - Adding custom icons to *all* scripts to make it obvious that it is a leap script, and also maybe from what package the script comes from as well!  Color coding and all that good stuff...

**Comment by Amarcolina** [comment]
Upgrading this issue to cover not just the graphic renderer but also all of our unity components.

**Comment by nickjbenson** [comment]
Would be super nice and I even spent some time deciding on color codes and organization, but ultimately I think it makes the most sense to stick with our current workflow: Refer to example scenes for features.

For AddComponentMenu specifically, our scripts still support being added in the menu via typing, which matches our current workflows anyway.

For icons, this would be a great nice-to-have, but if we want to revisit them, I think we should add Issues for them on a per-module basis, so that each issue is just a little more bite-size (and we can organize discussion around them).

**Comment by Amarcolina** [comment]
Fully agree!
