### ISSUE TITLE
Playback Module not serializing hands' Basis

### ISSUE THREAD

**Issue by nickjbenson** [leapmotion/UnityModules#777]
Received this from a developer via email.

> Specifically, I’m working with the Playback Module to record and play back serialized Frames. It’s working quite well, except the ‘Basis’ field of a frame is not being serialized, probably due to LeapTransform not being marked as Serializable. Since hands use that Basis to calculate the palm orientation, the palm is the only part, that’s not being played back correctly from a recorded frame. Would it be possible to make the LeapTransform Serializable as well?

**Comment by nickjbenson** [comment]
@Amarcolina Haven't we successfully serialized hand bases before?

If you have more details Julien, please feel free to add them to the thread.

**Comment by Amarcolina** [comment]
Does Julien have access to this ticket here?  I looked at the source and Basis is not actually a field at all, it is a property that calculates the transform on-the-fly whenever you ask for it, using the palm position and rotation to do so.  Since the palm position and rotation are both serialized properly I would expect the basis to behave as normal.  What kind of behavior are you seeing Julien?

**Comment by Amarcolina** [comment]
Whoops accidentally closed, re-opened :)

**Comment by nickjbenson** [comment]
OK, yeah I suspected something funky was going on like that. I've linked Julien to this thread so we'll hear more soon most likely.

**Comment by julienkay** [comment]
Ah yes, @Amarcolina you're completely right. I thought it was giving me a default value due to not being serialized.
However, I just realized that the problem actually is the Rotation that the Basis is calculated with. The Hand.Rotation is falsely serialized as the identity LeapQuaternion (0f, 0f, 0f, 1f), no matter what the actual orientation of the hand is during recording. I'll have too look into why that happens.

**Comment by julienkay** [comment]
Hmm, so the PlaybackRecorder uses CopyFromOtherExtensions.CopyFrom(this Frame frame, Frame source). But it seems, when calling that on a newly created frame, the Orientation is somehow not copied over? Can you confirm that that's not just happening on my side?

**Comment by Amarcolina** [comment]
I'll take a look, that does seem strange.  Are you using the most recent version of Unity Modules or an older version?

**Comment by julienkay** [comment]
Core Assets 4.2.1 and IE 1.0.1 yes.
Playback Module from develop branch.

**Comment by Amarcolina** [comment]
Oh dear, I see the issue hah.  Check out PlaybackProvider.cs lines 95-97.  Remove those and you should be good ;)

```
foreach(var hand in f.Hands) {
    hand.Rotation = LeapQuaternion.Identity;
}
```

**Comment by Amarcolina** [comment]
I created a PR to fix this as well
https://github.com/leapmotion/UnityModules/pull/779

**Comment by julienkay** [comment]
Wow, that's pretty obvious... Can't believe I didn't figure this out myself. *facepalm
Well, I don't have a Leap Motion with me right now, so it was kinda difficult to debug. Will check tomorrow, but thanks for the fix :)

**Comment by nickjbenson** [comment]
#779 just got merged  -- to test this fix Julien, I'd recommend just looking at the code change Alex made in that PR (since it's very minuscule) and seeing if that fixes your problem (rather than replacing your entire public Core release with our `develop` Core code)

Looks like we were zeroing out hand rotations for a legacy reason.

**Comment by julienkay** [comment]
Works like a charm. 👍 This can be closed.
I have another question/suggestion regarding Playback for which I'd create a separate issue if I may?

**Comment by Amarcolina** [comment]
Go for it!
