### ISSUE TITLE
Playback Support for IE by using LeapProvider rather than LeapServiceProvider

### ISSUE THREAD

**Issue by julienkay** [leapmotion/UnityModules#780]
Right now, Modules (i.e. the InteractionEngine) work with references to a LeapServiceProvider. I wanted to make Playback work with the InteractionEngine. So I wanted Hands using a PlaybackProvider to be able to interact with InteractionBehaviours. For this to work, I had to make a few minor modifications: I replaced the references to LeapServiceProvider in the static Hands class and the InteractionHand class with LeapProvider.

Conceptually this would make sense to me. The Interaction Engine would be independent from the implementation of the provider it gets its frames from. Be it a device, a recorded frame, frames sent through a network or whatever. I guess that abstraction is there for this reason anyway?

Now of course I don't know if there isn't another reason things have been done that way. For me, the example scenes seem to be working fine with my changes, both with recorded frames and normal use. What do you think?

**Comment by nickjbenson** [comment]
I took a look at InteractionHand.cs in the latest public release and it doesn't actually require a LeapServiceProvider at all, which was by design, to address exactly this sort of situation.

Actually, if you look for a `provider` property, you should see that InteractionHands can accept a custom LeapProvider to override its default provider; this should allow you to drive a set of InteractionHands by attaching them to the output of a PlaybackProvider in an Awake() method in a custom set-up script for the InteractionHands.

Give that a shot and see if it addresses your use-case. I'll qualify that by saying PlaybackProvider + InteractionHands is a totally untested combo! :D

As for Hands.Provider, I've also made that change before in internal projects. It's worth thinking about. @Amarcolina for thoughts.

**Comment by julienkay** [comment]
Yeah, you're right about InteractionHand.cs. I hought I had changed the Provider there too, but that's not the case.

I see now, that I could use the Custom HandDataMode to set my own provider. The only isue with this is however, that the InteractionControllerSwitcher.cs in line 128 still calls Hands.Left and Hands.Right every frame. This accesses the Provider property of the static Hands class (not InteractionHand), which is still a LeapServiceProvider. Accessing the property in turn does an expensive FindObjectOfType() call every frame. (Because I only have a PlaybackProvider set up in my scene so it never finds a LeapServiceProvider). Therefore OnLeftHandActive/OnLeftHandActive are never invoked. and hands not displayed.

So even though the Custom HandDataMode technically would work, but I'm back to the original problem: I need to change the Provider in the static Hands class from a LeapServiceProvider to a LeapProvider. In that case the setup already works automatically without needing to change the HandDataMode to custom (makes setup easier and I don't need to provide my own hand accessor functions), so I think it would be the right way to go.

**Comment by nickjbenson** [comment]
Ah, yeah, InteractionControllerSwitcher.cs was not made to be as generic as the rest of the InteractionEngine. Primarily that was intended to just be a utility script for the Example scenes.

OK, I do think HandUtils should provide `LeapProvider` rather than a `LeapServiceProvider`, although _if_ a `LeapServiceProvider` is present in the scene, it should default to that rather than any other `LeapProvider` so that a beginner isn't tripped up if they add an alternative `LeapProvider` but still have scripts relying on the default behavior of Hands.Left and Hands.Right.

I'll add this issue to the Core milestone for our next release; it's an easy change. In the mean time, feel free to keep the HandUtils.cs LeapServiceProvider -> LeapProvider change on your end; it should have no effect on any of our other example scenes or assets, and the change will be permanent when you upgrade to the next Core release.

**Comment by julienkay** [comment]
Thats great to hear :D
As I said, the InteractionHands work super fine, when driven by recorded frames otherwise.
