### ISSUE TITLE
Add a library of shaders as prototyping tools and examples to the GR

### ISSUE THREAD

**Issue by nickjbenson** [leapmotion/UnityModules#862]
For example, I use a relatively simple version of the Dynamic and Baked "Unlit" shader called "FakeLit" in our Particles project that uses normals relative to a light direction in object space to provide subtle shading on interface elements without actually paying any real lighting cost.

The core usability difference would be that developers get a nice set of options to pick from to make nice-looking panels straight from LeapPanelGraphics or LeapBoxGraphics when prototyping interfaces, without having to jump straight into shader-work.

Examples to include might be something like:
- "FakeLit", Baked/Dynamic versions
  - Could easily provide shaders with, say, Strong, Medium, and Subtle shading
- "Outline", Baked/Dynamic versions

If there are other effects we find we would want to be able to put on a UI-related material, an example shader that implements the effect is a good candidate for this sort of thing.

The inspiration for this idea comes from the fact that you get pretty harsh lighting when you enable "Use Normals" on an Unlit shader, and Standard Shaders are usually overkill for what I'm looking for when I'm trying to build something quickly and with low computational cost:

![image](https://user-images.githubusercontent.com/4485426/30398491-722e648a-9885-11e7-830e-79eca9d36865.png)

**Comment by Amarcolina** [comment]
So I don't think there would be a good outline shader we could use, since any basic outline effect
 - wouldn't work well for hard edges (a large part of GUI graphics)
 - wouldn't dynamically batch due to the multi-pass nature, causing lots of draw calls for dynamic renderer

For the lighting, might it be suitable to have the normal unlit shader have a lighting direction + lighting intensity parameters and leave it at that?
