### ISSUE TITLE
Ambiguous Reference in InteractionBehaviour.cs

### ISSUE THREAD

**Issue by dyanikoglu** [leapmotion/UnityModules#883]
**Versions**
Interaction Module : 1.1.0
Core Module: 4.3.3
Visual Studio 2017: 15.3.5

**Problem Definition**
OnGraspedMovement event is defined as

`public Action<Vector3, Quaternion, Vector3, Quaternion, List<InteractionController>> OnGraspedMovement
      = (preSolvedPos, preSolvedRot, solvedPos, solvedRot, graspingControllers) => { };`

in InteractionBehaviour class. Because of including both of **System** and **Leap.Unity.Interaction.Internal**, the Action reference becomes ambiguous. This causes compile error in Visual Studio 2017

**Resolution**
Event definition should be changed as

`public Leap.Unity.Interaction.Internal.Action<Vector3, Quaternion, Vector3, Quaternion, List<InteractionController>> OnGraspedMovement
      = (preSolvedPos, preSolvedRot, solvedPos, solvedRot, graspingControllers) => { };`

**Comment by Amarcolina** [comment]
Yikes, no good!  My suggestion @nickjbenson would be to create specific named delegates for those callbacks, that way there is never a risk of name clash, whether or not unity is using the new scripting engine.

**Comment by nickjbenson** [comment]
Yes! Sorry, meant to respond to this earlier.

I think the correct answer is definitely to just give it a named delegate. The five-parameter Action idea wasn't so great because it also pollutes Visual Studio's automatic suggestions for `using` statements when you don't have `using System;`

If you don't mind @dyanikoglu, I'll put a PR together to change the callback to use a named delegate instead of merging your de-ambiguation PR.

**Comment by dyanikoglu** [comment]
@nickjbenson Ok then, just wanted to make a heads-up for this little issue.

Thank you.

**Comment by nickjbenson** [comment]
Got the resolution here:
https://github.com/leapmotion/UnityModules/pull/918

👍
