### ISSUE TITLE
AddComponentMenu empty tag in various classes

### ISSUE THREAD

**Issue by tomy93** [leapmotion/UnityModules#954]
The AddComponentMenu Unity attribute requires to enter a tag to be able to add this MonoBehaviour to a GameObject from the Editor, being empty ("") makes imposible to attach it because it don't appears in the Component Menu. This is useful when is a base class as AttachmentHand.cs, but not in utility classes as SimpleInteractionGlow.
![image](https://user-images.githubusercontent.com/12350256/35989141-6a5663ee-0cce-11e8-99f6-6a259d204f29.png)

**Comment by nickjbenson** [comment]
As an immediate workaround, you can drag the script into the Inspector from the Project tab to add a script that has its Component Menu entry hidden in this way.

We're very sensitive to how we populate our primary discoverability affordances: Intellisense in Visual Studio when writing new scripts that include the `Leap.Unity` namespace, and the Component Menu when Core or any Modules is imported into Unity. I hid the SimpleInteractionGlow script from the component menu because it wasn't intended to be used as a script so much as an API reference. We have a bunch of scripts like this that aren't intended to be used directly but that drive our example scenes.

We can consider making SimpleInteractionGlow specifically into more of a first-class utility script, but would that fully address your ask in this issue? It sounds like you're arguing that we should have many other of our example-only classes be made accessible in the component menu.

**Comment by tomy93** [comment]
Thanks a lot for your deep explanation.
I didn't knew that it was made on purpose, it looked as an error for me (that someone forgot to put a tag in the attribute) because I couldn't attach that script from the AddComponent button in the Inspector. 
Another simple workaround for devs like me that use those kind of classes a lot is to just remove that attribute line.

**Comment by nickjbenson** [comment]
Closing. Thanks for raising the issue, @tomy93. If we see more confusion on this, we can start organizing scripts like this into an "Examples" category as an alternative.
